"""Phase 10 Q&A matrix runner (live end-to-end, E-10).

Drives the full pipeline via the FastAPI TestClient against the REAL local index.
Structured facts / refusals / scope / PII / no-source resolve WITHOUT Groq;
only educational & process (retrieval → generation) rows call Groq. Writes a
Markdown matrix to Docs/qa_matrix.md (feeds the README sample Q&A).

Run:  python -m scripts.qa_matrix
"""

from __future__ import annotations

from pathlib import Path

from fastapi.testclient import TestClient

from backend import main

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "Docs" / "qa_matrix.md"

# (category, query). Educational/process rows hit Groq; the rest are deterministic.
QUERIES: list[tuple[str, str]] = [
    ("Factual (fact table)", "What is the expense ratio of HDFC Mid Cap Fund?"),
    ("Factual (fact table)", "What is the lock-in period of HDFC ELSS Tax Saver?"),
    ("Factual (fact table)", "What is the minimum SIP for HDFC Small Cap Fund?"),
    ("Factual (fact table)", "What is the AUM of HDFC Large Cap Fund?"),
    ("Factual (fact table)", "How much tax deduction does HDFC ELSS give under 80C?"),
    ("Factual (lock-in, non-ELSS)", "What is the lock-in period of HDFC Mid Cap Fund?"),
    ("Factual (LLM · education)", "What is a mutual fund?"),
    ("Factual (LLM · education)", "What are the types of mutual fund schemes?"),
    ("Factual (LLM · process)", "How do I download a consolidated account statement?"),
    ("Factual (LLM · process)", "How do I get a capital gains statement for mutual funds?"),
    ("Factual (LLM · scheme)", "What is the riskometer level of HDFC Mid Cap Fund?"),
    ("Factual (LLM · scheme)", "Who manages HDFC Flexi Cap Fund?"),
    ("Advisory (refused)", "Should I invest in HDFC Mid Cap Fund?"),
    ("Advisory (refused)", "Which is better, HDFC Mid Cap or HDFC Small Cap?"),
    ("Advisory (refused)", "Will HDFC ELSS NAV go up next year?"),
    ("Out of scope", "What is the expense ratio of SBI Small Cap Fund?"),
    ("Out of scope", "What is the expense ratio of HDFC Balanced Advantage Fund?"),
    ("Out of scope", "What's the weather in Mumbai today?"),
    ("PII rejected", "My PAN is ABCDE1234F, what is the expense ratio of HDFC Mid Cap?"),
    ("No source", "What is the portfolio turnover churn ratio of HDFC Mid Cap Fund?"),
]


def _first_line(text: str) -> str:
    return (text or "").strip().split("\n\n")[0].replace("\n", " ").strip()


def main_run() -> None:
    client = TestClient(main.app)
    rows = []
    groq_hits = 0

    for category, q in QUERIES:
        resp = client.post("/api/query", json={"query": q})
        body = resp.json()
        rtype = body["response_type"]
        if rtype == "FACTUAL" and "LLM" in category:
            groq_hits += 1
        answer = _first_line(body["answer"])
        src = body.get("source_url") or "—"
        rows.append((category, q, rtype, answer, src))
        print(f"[{rtype:16}] {q}")
        print(f"    -> {answer}")
        if src != "—":
            print(f"    src: {src}")

    lines = [
        "# Q&A Matrix — live end-to-end verification (Phase 10 / E-10)",
        "",
        "> Generated by `python -m scripts.qa_matrix` against the real local index.",
        "> Structured facts / refusals / scope / PII / no-source are deterministic",
        "> (no LLM); educational & process rows use Groq for grounded generation.",
        "",
        "| Category | Question | response_type | Answer (first line) | Source |",
        "|---|---|---|---|---|",
    ]
    for category, q, rtype, answer, src in rows:
        a = answer.replace("|", "\\|")
        s = "—" if src == "—" else f"[link]({src})"
        lines.append(f"| {category} | {q} | `{rtype}` | {a} | {s} |")
    lines += ["", f"_Total queries: {len(rows)} · Groq-generated rows: {groq_hits}_", ""]

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {OUT} ({len(rows)} rows, {groq_hits} Groq calls).")


if __name__ == "__main__":
    main_run()
